// Run with: node tests/cost-ledger.test.cjs
// The test extracts the same function used by index.html, so it detects regressions in the deployed code.
const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const start=html.indexOf('function orderedTransactions(items){');
const end=html.indexOf('\nfunction renderOverview()',start);
assert.ok(start>=0&&end>start,'chronological ordering and cost ledger functions must exist');
const source=html.slice(start,end);
const calculate=new Function('trades',source+';return estimateCostLedger()');
function run(trades,ticker='2330'){const result=calculate(trades);return {state:result.states.get(ticker),warnings:result.warnings};}
const buy={ticker:'2330',trade_date:'2026-01-01',transaction_type:'現股',quantity:100,price:50,trade_fees:20};
const sell={ticker:'2330',trade_date:'2026-01-02',transaction_type:'現股',quantity:-40,price:60,trade_fees:10};
let x=run([buy,sell]);
assert.equal(x.state.quantity,60);
assert.equal(x.state.cost,3012);
assert.equal(x.state.realized,382);
assert.equal(x.state.valid,true);
x=run([buy,{ticker:'2330',trade_date:'2026-01-02',transaction_type:'股票股利',quantity:20}]);
assert.equal(x.state.quantity,120);
assert.equal(x.state.cost,5020);
x=run([buy,{...sell,quantity:-101},{...buy,trade_date:'2026-01-03'}]);
assert.equal(x.state.valid,false);
assert.equal(x.state.quantity,100);
assert.ok(x.warnings.length>=2);
x=run([{...buy,price:null}]);
assert.equal(x.state.valid,false);
x=run([buy,{ticker:'2330',trade_date:'2026-01-02',transaction_type:'現金股息',dividend_gross:100}]);
assert.equal(x.state.cost,5020);
x=run([sell,buy]);
assert.equal(x.state.valid,true,'unsorted input must be ordered by trade date');
assert.equal(x.state.realized,382);
x=run([buy,{...buy,trade_date:'2026-01-03',quantity:100,price:70,trade_fees:0},{...sell,trade_date:'2026-01-04',quantity:-100,price:80,trade_fees:0}]);
assert.equal(x.state.quantity,100);
assert.equal(x.state.cost,6010);
assert.equal(x.state.realized,1990);
x=run([buy,{...sell,quantity:-100,price:55,trade_fees:0}]);
assert.equal(x.state.quantity,0);
assert.equal(x.state.cost,0);
assert.equal(x.state.realized,480);
x=run([buy,{...buy,ticker:'0050',price:20,quantity:10,trade_fees:0}]);
assert.equal(x.state.quantity,100);
assert.equal(run([buy,{...buy,ticker:'0050',price:20,quantity:10,trade_fees:0}],'0050').state.cost,200);
x=run([buy,{...buy,trade_date:'2026-01-02',price:'',quantity:10}]);
assert.equal(x.state.valid,false);
x=run([{...buy,trade_fees:null}]);
assert.equal(x.state.valid,false,'missing fees must not be silently treated as zero');
x=run([{...buy,trade_fees:0}]);
assert.equal(x.state.valid,true,'explicit zero fees are allowed');
assert.equal(x.state.cost,5000);
x=run([buy,{ticker:'2330',trade_date:'2026-01-02',transaction_type:'股票股利',quantity:20,trade_fees:0}]);
assert.equal(x.state.valid,true,'stock dividend with explicit zero fee should pass');
assert.equal(x.state.quantity,120);
x=run([buy,{ticker:'2330',trade_date:'2026-01-02',transaction_type:'股票股利',quantity:20,trade_fees:5}]);
assert.equal(x.state.valid,false,'stock dividend with nonzero trading fee needs manual review');
x=run([{...buy,quantity:1988,price:1.5,trade_fees:0,paid_cost:2883}]);
assert.equal(x.state.quantity,1988);
assert.equal(x.state.cost,2883,'Subscription refund is already included in explicit paid cost');
x=run([{...buy,paid_cost:-1}]);
assert.equal(x.state.valid,false,'Invalid explicit cost must not fall back to a guessed cost');
console.log('PASS: 16 cost ledger cases (sale, stock dividend, oversell, missing price, cash dividend, chronological sorting, multiple buys, full liquidation, ticker separation, empty price)');
