const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const source=html.slice(html.indexOf('function orderedTransactions(items){'),html.indexOf('function renderOverview(){'));
const calculate=new Function('trades',source+';return excelCostLedger()');
const buy={ticker:'TEST',trade_date:'2026-01-01',transaction_type:'現股',quantity:100,price:20,trade_fees:5,paid_cost:2005};
const sell={...buy,trade_date:'2026-01-02',quantity:-40,price:25,trade_fees:3,paid_cost:null};
const div={ticker:'TEST',trade_date:'2026-01-03',transaction_type:'現金股息',dividend_gross:100,wire_fee:5,payment_confirmed:true};
const run=rows=>calculate(rows).states.get('TEST');
let st=run([buy,sell,div]);assert.equal(st.quantity,60);assert.equal(st.cost,913);assert.equal(st.valid,true);
st=run([{...buy,paid_cost:1905}]);assert.equal(st.cost,1905);
st=run([buy,{ticker:'TEST',trade_date:'2026-01-04',transaction_type:'股票股利',quantity:20}]);assert.equal(st.quantity,120);assert.equal(st.cost,2005);
st=run([buy,{...sell,quantity:-90,price:30,trade_fees:0},div]);assert.equal(st.quantity,10);assert.equal(st.cost,-790);
st=run([buy,{...sell,quantity:-100,price:25,trade_fees:5},div]);assert.equal(st.quantity,0);assert.equal(-st.cost,585);
st=run([buy,{...div,wire_fee:null,payment_confirmed:false}]);assert.equal(st.cost,1905);assert.equal(st.pendingDividends,1);
st=run([buy,{...div,wire_fee:0,payment_confirmed:false}]);assert.equal(st.pendingDividends,0);
st=run([{...buy,paid_cost:null,trade_fees:null}]);assert.equal(st.valid,false);
st=run([{...buy,paid_cost:0}]);assert.equal(st.cost,0);assert.equal(st.valid,true);
st=run([buy,{...sell,quantity:-101}]);assert.equal(st.valid,false);
st=run([div,sell,buy]);assert.equal(st.cost,913);
st=run([buy,{...sell,paid_cost:200}]);assert.equal(st.cost,1008);
assert.ok(html.includes('excelCostBody'));assert.ok(!html.includes("['成本／損益','待核對']"));assert.ok(html.includes('obj.paid_cost=null'));
console.log('PASS: Excel net outlay, dividends, refund, liquidation, negative cost, missing inputs and edit invalidation');
