// Read-only Excel duplicate-key preflight regression tests.
// Run: node tests/import-preflight.test.cjs
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
assert.match(html,/sheet_to_json\(book\.Sheets\[sheetName\],\{header:1,defval:'',raw:true\}\)/,'Transaction worksheet must use raw Excel dates');
assert.match(html,/missingCodeRows=candidateRows\.filter/,'Transactions with missing tickers must be audited');
assert.match(html,/const blockers=\[\];/,'Import safety gate must exist');
assert.match(html,/if\(missingCodeRows\.length\)blockers\.push/,'Missing tickers must block import');
assert.match(html,/if\(potentialCloudMatches\.length\)blockers\.push/,'Cloud duplicate candidates must block import');
assert.match(html,/目前正式匯入功能維持關閉/,'Import must remain disabled until validated');
assert.match(html,/normalize\('NFKC'\)/,'Excel headers must normalize full-width characters');
assert.match(html,/手續費＆交易稅/,'Source Excel fee header must be recognized');
assert.match(html,/入賬時間/,'Source Excel payout header must be recognized');
assert.ok(html.includes('const conversionErrors=[],convertedTrades=[];'),'Typed import conversion must exist');
assert.ok(html.includes('sequence_no:position'),'Import must preserve original Excel order');
assert.ok(html.includes('dividend_gross:gross'),'Import must convert net dividends to gross');
assert.ok(html.includes('if(conversionErrors.length)blockers.push'),'Invalid conversions must block import');
assert.ok(html.includes('6201 與 006201 永遠是不同代號'),'Leading-zero distinction must be documented');
assert.ok(html.includes('const normalizeTicker=v=>'),'Ticker normalizer must exist');
assert.ok(html.includes('internalConflictCodes.add(code)'),'Internal name conflicts must be tracked by exact code');
assert.ok(html.includes('cloudConflictCodes.add(code)'),'Cloud name conflicts must be tracked by exact code');
assert.ok(html.includes('new Set([...internalConflictCodes,...cloudConflictCodes])'),'Conflict detection must not parse display messages');
assert.ok(!html.includes('new Set(nameIssues.map(issue=>'),'Conflict detection must not depend on warning text');
assert.ok(html.includes("const waitingRows=suspect.filter"),'Pending trade plans must be classified separately');
assert.ok(html.includes("const refundRows=suspect.filter"),'Capital refunds must be classified separately');
assert.ok(html.includes("const remainingSuspect=suspect.filter(item=>!specialRows.has(item))"),'Recognized special rows must not be reported as unknown trades');
assert.ok(html.includes("等待不代表成交"),'Pending trades must not be counted as executed');
assert.ok(html.includes('const reviewByRow=new Map()'),'Review queue must group reasons per Excel row');
assert.ok(html.includes('reviewRows.map(([position,reasons])'),'Every flagged row must be rendered');
assert.ok(html.includes('Excel 原始列號'),'Original row reference must remain visible');
assert.ok(html.includes('僅本機預檢，不代表已匯入'),'Review must not pretend to be persisted');
assert.ok(html.includes('const reviewExport={'),'Review export must be built from full review list');
assert.ok(html.includes('rows:reviewRows.map'),'Review export must include every flagged row');
assert.ok(html.includes("status:'待確認'"),'Review export must preserve pending status');
assert.ok(html.includes('cloud_write_performed:false'),'Review export must not claim cloud writes');
assert.ok(html.includes('id="exportImportReview"'),'Review export download control must exist');
const start=html.indexOf('  const canonical=v=>',html.indexOf('// Compare only unambiguous dates'));
const end=html.indexOf('  const dateAudit={missing:[],invalid:[]};',start);
assert.ok(start>0&&end>start,'Excel normalization helpers must exist');
const helpers=html.slice(start,end);
const XLSX={SSF:{parse_date_code(n){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return {y:d.getUTCFullYear(),m:d.getUTCMonth()+1,d:d.getUTCDate()};}}};
const make=new Function('XLSX','dateCol','codeCol','typeCol','sharesCol','priceCol','dividendCol','wireCol',helpers+';return {strictDate,numberKey,signatureParts,signature};');
const x=make(XLSX,0,1,2,3,4,5,6);
assert.equal(x.strictDate('2026/9/1'),'2026-09-01');
assert.equal(x.strictDate('2026-09-01'),'2026-09-01');
assert.equal(x.strictDate('5/6/16'),null);
assert.equal(x.strictDate('42496'),'2016-05-06');
assert.equal(x.strictDate('2026/02/30'),null);
assert.equal(x.numberKey('1,000.00'),'1000');
assert.equal(x.numberKey('10.50'),'10.5');
assert.equal(x.numberKey(''),null);
assert.equal(x.signatureParts('2026/9/1','0056','現股','1,000','72.20'),x.signatureParts('2026-09-01','0056','現股',1000,72.2));
assert.notEqual(x.signatureParts('2026/9/1','0056','現股',1000,72.2),x.signatureParts('2026/9/1','0056','現股',500,72.2));
assert.equal(x.signatureParts('5/6/16','0056','現股',1000,72.2),null);
assert.equal(x.signatureParts('2026/9/1','0056','股票股利',100,null),x.signatureParts('2026/9/1','0056','股票股利',100,0));
assert.notEqual(x.signatureParts('2026/9/1','6201','股票股利',100,null),x.signatureParts('2026/9/1','006201','股票股利',100,null));
assert.equal(x.signatureParts('2026/9/1','0056','現金股息',null,null,105,5),x.signatureParts('2026/9/1','0056','現金股息',null,null,105,5));
assert.notEqual(x.signatureParts('2026/9/1','0056','現金股息',null,null,105,5),x.signatureParts('2026/9/1','0056','現金股息',null,null,100,5));
assert.equal(x.signature([46000,'0056','現金股息',null,null,100,5]),x.signatureParts(46000,'0056','現金股息',null,null,105,5));
console.log('PASS: Excel preflight normalization and source-format guards');
