// Read-only Excel duplicate-key preflight regression tests.
// Run: node tests/import-preflight.test.cjs
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
assert.match(html,/sheet_to_json\(book\.Sheets\[sheetName\],\{header:1,defval:'',raw:true\}\)/,'Transaction worksheet must use raw Excel dates');
assert.match(html,/missingCodeRows=candidateRows\.filter/,'Transactions with missing tickers must be audited');
assert.match(html,/const blockers=\[\];/,'Import safety gate must exist');
assert.match(html,/if\(missingCodeRows\.length\)blockers\.push/,'Missing tickers must block import');
assert.match(html,/if\(potentialCloudMatches\.length\)blockers\.push/,'Cloud duplicate candidates must block import');
assert.match(html,/目前正式匯入功能維持關閉/,'Import must remain disabled until validated');
assert.match(html,/normalize\('NFKC'\)/,'Excel headers must normalize full-width characters');
assert.match(html,/手續費＆交易稅/,'Source Excel fee header must be recognized');
assert.match(html,/入賬時間/,'Source Excel payout header must be recognized');
assert.ok(html.includes('const conversionErrors=[],convertedTrades=[];'),'Typed import conversion must exist');
assert.ok(html.includes('sequence_no:position'),'Import must preserve original Excel order');
assert.ok(html.includes('dividend_gross:gross'),'Import must convert net dividends to gross');
assert.ok(html.includes('if(conversionErrors.length)blockers.push'),'Invalid conversions must block import');
const start=html.indexOf('  const canonical=v=>',html.indexOf('// Compare only unambiguous dates'));
const end=html.indexOf('  const dateAudit={missing:[],invalid:[]};',start);
assert.ok(start>0&&end>start,'Excel normalization helpers must exist');
const helpers=html.slice(start,end);
const XLSX={SSF:{parse_date_code(n){const d=new Date(Date.UTC(1899,11,30)+n*86400000);return {y:d.getUTCFullYear(),m:d.getUTCMonth()+1,d:d.getUTCDate()};}}};
const make=new Function('XLSX','dateCol','codeCol','typeCol','sharesCol','priceCol',helpers+';return {strictDate,numberKey,signatureParts,signature};');
const x=make(XLSX,0,1,2,3,4);
assert.equal(x.strictDate('2026/9/1'),'2026-09-01');
assert.equal(x.strictDate('2026-09-01'),'2026-09-01');
assert.equal(x.strictDate('5/6/16'),null);
assert.equal(x.strictDate('42496'),'2016-05-06');
assert.equal(x.strictDate('2026/02/30'),null);
assert.equal(x.numberKey('1,000.00'),'1000');
assert.equal(x.numberKey('10.50'),'10.5');
assert.equal(x.numberKey(''),null);
assert.equal(x.signatureParts('2026/9/1','0056','現股','1,000','72.20'),x.signatureParts('2026-09-01','0056','現股',1000,72.2));
assert.notEqual(x.signatureParts('2026/9/1','0056','現股',1000,72.2),x.signatureParts('2026/9/1','0056','現股',500,72.2));
assert.equal(x.signatureParts('5/6/16','0056','現股',1000,72.2),null);
console.log('PASS: Excel preflight normalization and source-format guards');
